config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :judges, only: [:new, :create, :index, :update]
  root to: 'tree#index'
end

app/models/judge.rb
class Judge
  include Mongoid::Document

  field :name
  field :level
  field :country, default: 'br'

  has_many :child_judges, :class_name => 'Judge', inverse_of: :parent_judge
  belongs_to :parent_judge, :class_name => 'Judge', inverse_of: :child_judges

  validates_presence_of :name, :level

  LEVEL_WORDS = {"1" => "one", "2" => "two", "3" => "three", "4" => "four", "5" => "five", "Inativo" => "inativo", "Emeritus" => "emeritus"}
  
  def self.levels
    ["1", "2", "3", "4", "5", "Inativo", "Emeritus"]
  end

  def level_to_word
    LEVEL_WORDS[level]
  end
  def level_output
    if level == "Inativo" || level == "Emeritus"
      level
    else
      #t(:level) #{level}
      "Nível #{level}"
    end
  end
  def name_output
    name_parts = name.split(' ')
    if name_parts.count > 2
      "#{name_parts.first} #{name_parts.last}"
    else
      name
    end
  end
  def country_output
    unless country.downcase == "br"
      "<div class='flag flag-#{country.downcase}' title='#{IsoCountryCodes.find(country).name}'></div>"
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_info
  def new
    @judge = Judge.new
  end
  def create
    @judge = Judge.new(judge_params)
    if @judge.save
      redirect_to :root, notice: 'Juiz criado'
    else
      flash[:error] = "Erro ao criar Juiz"
      render 'new'
    end
  end
  def index
  end
  def update
    @judge = Judge.find(params[:id])
    @judge.update_attributes(judge_params)
    redirect_to judges_path
  end

  private
  def judge_params
    params.require(:judge).permit(:name, :level, :parent_judge_id, :country)
  end
  def load_info
    @judges = Judge.asc(:name)
    @countries = IsoCountryCodes.for_select.sort_by{|c| c.first}
  end
end

app/controllers/tree_controller.rb
class TreeController < ApplicationController
  def index
    @judge_count = Judge.count
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Name' )
    data_table.new_column('string', 'Parent')
    data_table.new_column('string', 'Tip')
    data_table.add_rows(Judge.all.asc(:name).collect{|j| [{v: j.id.to_s, f:"<div class='judge #{j.level_to_word}'><p>#{j.name_output}</p><div class='level'>#{j.level_output}#{j.country_output}</div></div>"}, j.parent_judge.try(:id).try(:to_s), "#{j.name} (#{j.level})"]})

    @chart = GoogleVisualr::Interactive::OrgChart.new(data_table, {allowHtml: true})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/judges/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Level</th>
    <th>Father</th>
    <th>Country</th>
    <th></th>
  </tr>
  <%@judges.each do |j|%>
    <tr>
      <%= form_for j do |f|%>
      <td><%=j.name%></td>
      <td>
        <%= select_tag 'judge[level]', options_for_select(Judge.levels, j.level),{class: 'form-control'} %>
      </td>
      <td>
        <%= select_tag 'judge[parent_judge_id]', options_for_select(@judges.collect{|j| [j.name, j.id]}, j.parent_judge_id),{class: 'form-control', prompt: 'Father'} %>
      </td>
      <td>
        <%= select_tag 'judge[country]', options_for_select(@countries, j.country.upcase),{class: 'form-control'} %>
      </td>
      <td><button type="submit" class="btn btn-primary">Update</button></td>
      <%end%>
    </tr>
  <%end%>
</table>

app/views/judges/new.html.erb
<%=form_for @judge, html: {class: "form-horizontal col-sm-8", role: "form"} do |f|%>
<div class="form-group">
  <%=f.label :name, class: "col-sm-2 control-label"%>
  <div class="col-sm-6">
    <%=f.text_field :name, class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <%=f.label :level, class: "col-sm-2 control-label" %>
  <div class="col-sm-6">
    <%= select_tag 'judge[level]', options_for_select(Judge.levels),{class: 'form-control'} %>    
  </div>
</div>
<div class="form-group">
  <%= f.label :father, class: "col-sm-2 control-label" %>
  <div class="col-sm-6">
    <%= select_tag 'judge[parent_judge_id]', options_for_select(@judges.collect{|f| [f.name, f.id]}),{prompt: 'Father', class: 'form-control'} %>
  </div>
</div>
<div class="form-group">
  <%= f.label :country, class: "col-sm-2 control-label" %>
  <div class="col-sm-6">
    <%= select_tag 'judge[country]', options_for_select(@countries, 'BR'),{prompt: 'Country', class: 'form-control', selected: 'br'} %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-6">
    <button type="submit" class="btn btn-primary">Create</button>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%=t :web_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <meta property="og:title" content="<%=t :web_title %>"/>
  <meta property="og:url" content="<%=root_url%>"/>
  <meta property="og:site_name" content="Juízes Magic Brasil"/>
  <meta property="og:image" content="<%=asset_url('tree.jpg') %>"/>
  <meta property="og:description" content="<%=t :web_description %>"/>
  <%= csrf_meta_tags %>
  <style>
  table{border-collapse: initial !important;}
  .bs-callout {
    margin: 20px 0;
    padding: 15px 30px 15px 15px;
    border-left: 5px solid #eee;
  }
  .bs-callout h4 {
    margin-top: 0;
  }
  .bs-callout p:last-child {
    margin-bottom: 0;
  }
  .bs-callout code,
  .bs-callout .highlight {
    background-color: #fff;
  }

  /* Themes for different contexts */
  .bs-callout-danger {
    background-color: #fcf2f2;
    border-color: #dFb5b4;
  }
  .bs-callout-warning {
    background-color: #fefbed;
    border-color: #f1e7bc;
  }
  .bs-callout-info {
    background-color: #f0f7fd;
    border-color: #d0e3f0;
  }
  .judge{width: 80px;height: 80px;vertical-align: middle;}
  .judge p{min-height: 40px;}
  .emeritus{background: #CCCC33;}
  .three{background: #CCCCFF;}
  .two{background: #99CCFF;}
  .inativo{background: #E0E0E0;}
  .level{color: blue;text-decoration: italic;font-size: 12px;}
  td div.flag{ margin: 0 auto;}
  .google-visualization-orgchart-node{font-size: 14px !important;padding:0px !important;}
  </style>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%=link_to t('judges_comunity'), root_path, class:'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li>
            <%=link_to t('new_judge'), new_judge_path%>
          </li>
          <li>
            <%=link_to t('judges'), judges_path%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%=link_to t('log_out'), destroy_user_session_path, method: :delete %>
          </li>
        </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <%if flash[:error] %>
    <div class='bs-callout bs-callout-warning'>
      <h4><%=flash[:error]%></h4>
    </div>
    <% end %>
    <%if flash[:notice] %>
    <div class='bs-callout bs-callout-info'>
      <h4><%=flash[:notice]%></h4>
    </div>
    <% end %>

    <%= yield %>
  </div>
  <%= yield :javascript %>
</body>
</html>

app/views/tree/index.html.erb
<div class="page-header">
  <h1>Family Tree <small><%=t :web_description %> (<%=@judge_count%></span> <%=t :Judges %>)</small></h1>
</div>

<div id="tree"></div>
<%= render_chart(@chart, 'tree') %>